### ISSUE TITLE
Unable to run after startup

### ISSUE THREAD

**Issue by AlanKrueger** [Xjph/EliteObservatory#36]
I previously had a version installed early last year, but I had uninstalled it. I reinstalled this just the v0.5.21.014 release via the MSI tonight and couldn't get the app to launch.

When I look in the Windows Event Viewer, I see this error happens each time I try to run the app:
```
Application: Observatory.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Xml.XmlException
   at System.Xml.XmlTextReaderImpl.Throw(System.Exception)
   at System.Xml.XmlTextReaderImpl.Throw(System.String, System.String[])
   at System.Xml.XmlTextReaderImpl.ParseText(Int32 ByRef, Int32 ByRef, Int32 ByRef)
   at System.Xml.XmlTextReaderImpl.ParseText()
   at System.Xml.XmlTextReaderImpl.ParseElementContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XmlTextReader.Read()
   at System.Xml.XmlTextReaderImpl.Skip()
   at System.Xml.XmlTextReader.Skip()
   at System.Configuration.XmlUtil.StrictSkipToNextElement(System.Configuration.ExceptionAction)
   at System.Configuration.BaseConfigurationRecord.ScanSectionsRecursive(System.Configuration.XmlUtil, System.String, Boolean, System.String, System.Configuration.OverrideModeSetting, Boolean)
   at System.Configuration.BaseConfigurationRecord.ScanSectionsRecursive(System.Configuration.XmlUtil, System.String, Boolean, System.String, System.Configuration.OverrideModeSetting, Boolean)
   at System.Configuration.BaseConfigurationRecord.ScanSections(System.Configuration.XmlUtil)
   at System.Configuration.BaseConfigurationRecord.InitConfigFromFile()

Exception Info: System.Configuration.ConfigurationErrorsException
   at System.Configuration.ConfigurationSchemaErrors.ThrowIfErrors(Boolean)
   at System.Configuration.BaseConfigurationRecord.ThrowIfParseErrors(System.Configuration.ConfigurationSchemaErrors)
   at System.Configuration.Configuration..ctor(System.String, System.Type, System.Object[])
   at System.Configuration.ClientConfigurationHost.OpenExeConfiguration(System.Configuration.ConfigurationFileMap, Boolean, System.Configuration.ConfigurationUserLevel, System.String)
   at System.Configuration.ConfigurationManager.OpenExeConfigurationImpl(System.Configuration.ConfigurationFileMap, Boolean, System.Configuration.ConfigurationUserLevel, System.String, Boolean)
   at System.Configuration.ClientSettingsStore.ReadSettingsFromFile(System.String, System.String, Boolean)
   at System.Configuration.LocalFileSettingsProvider.GetSettingValuesFromFile(System.String, System.String, Boolean, System.Configuration.SettingsPropertyCollection)
   at System.Configuration.LocalFileSettingsProvider.Upgrade(System.Configuration.SettingsContext, System.Configuration.SettingsPropertyCollection, Boolean)
   at System.Configuration.LocalFileSettingsProvider.Upgrade(System.Configuration.SettingsContext, System.Configuration.SettingsPropertyCollection)
   at System.Configuration.ApplicationSettingsBase.Upgrade()
   at Observatory.Observatory.Main()
```

**Comment by Xjph** [comment]
That appears to be a crash while trying to load/migrate the settings file from the older version. That process is all handled internally by .NET so it's interesting to me that it's crashing like that.

Regardless, you should be able to launch successfully if you delete your existing settings files in %localappdata%\Observatory.

**Comment by AlanKrueger** [comment]
That seems to do the trick. Thanks!
